### ISSUE TITLE
[question]do you know how to set airplay fps?

### ISSUE THREAD

**Issue by ShiverZm** [rabits/wlroots-airplay-screen-mirror#2]
i want to make apple send me video data for 60 fps but i try some refresh parameter,it did not work? bro ,did you know something?

**Comment by rabits** [comment]
Hi @ShiverZm , nope) I work with airplay protocol, but not with apple devices.

**Comment by ShiverZm** [comment]
@rabits   Sure is it Protocol,i knew some software can refresh Video for 60 fps,but i try for many method,they did not work.

**Comment by ShiverZm** [comment]
> @rabits Sure is it Protocol,i knew some software can refresh Video for 60 fps,but i try for many method,they did not work.

refresh Mirror
